namespace SimpleTransClassesOfPostNum1.SimpleHTables;

public enum CsvFilesHelperTable
{
    TextsPatch,
    Accessories,
    Locales,
    Globals,
    Resources,
    Projectiles,
    Regions,
    GameModeVariation,
    Locations,
    LocationThemes,
    Music,
    Emotes,
    Milestones,
    Messages,
    BillingPackages,
    Sounds,
    Effects,
    ParticleEmitters,
    HealthBars,
    ClientGlobals,
    Credits,
    Characters,
    AreaEffects,
    Items,
    Maps,
    Skills,
    Campaign,
    Bosses,
    Cards,
    Animations,
    Faces,
    AllianceRoles,
    AllianceBadges,
    Tutorial,
    Tiles,
    NameColors,
    PlayerThumbnails,
    Skins,
    Themes,
    SkinConfs,
    Sprays,
    Hints,
    Links,
    EmoteBundles,
    PlayerMapEnvironments,
    MapTemplates,
    RankedLocations,
    RankedRanks,
    Carryables,
    GearBoosts,
    GearLevels,
    AllianceLeagueModes,
    AllianceLeagueRanks,
    ShopPanelLayouts,
    ShopStyleSets
}

public static class CsvFilesHelperTableExtensions
{
    public static string GetFileName(this CsvFilesHelperTable fileId)
    {
        return fileId switch
        {
            CsvFilesHelperTable.TextsPatch => "texts_patch.csv",
            CsvFilesHelperTable.Accessories => "accessories.csv",
            CsvFilesHelperTable.Locales => "locales.csv",
            CsvFilesHelperTable.Globals => "globals.csv",
            CsvFilesHelperTable.Resources => "resources.csv",
            CsvFilesHelperTable.Projectiles => "projectiles.csv",
            CsvFilesHelperTable.Regions => "regions.csv",
            CsvFilesHelperTable.Locations => "locations.csv",
            CsvFilesHelperTable.Music => "music.csv",
            CsvFilesHelperTable.Emotes => "emotes.csv",
            CsvFilesHelperTable.Milestones => "milestones.csv",
            CsvFilesHelperTable.Messages => "messages.csv",
            CsvFilesHelperTable.LocationThemes => "location_themes.csv",
            CsvFilesHelperTable.BillingPackages => "billing_packages.csv",
            CsvFilesHelperTable.Sounds => "sounds.csv",
            CsvFilesHelperTable.Effects => "effects.csv",
            CsvFilesHelperTable.ParticleEmitters => "particle_emitters.csv",
            CsvFilesHelperTable.HealthBars => "health_bars.csv",
            CsvFilesHelperTable.ClientGlobals => "client_globals.csv",
            CsvFilesHelperTable.Credits => "credits.csv",
            CsvFilesHelperTable.Characters => "characters.csv",
            CsvFilesHelperTable.AreaEffects => "area_effects.csv",
            CsvFilesHelperTable.Items => "items.csv",
            CsvFilesHelperTable.GameModeVariation => "game_mode_variations.csv",
            CsvFilesHelperTable.Maps => "maps.csv",
            CsvFilesHelperTable.Skills => "skills.csv",
            CsvFilesHelperTable.Campaign => "campaign.csv",
            CsvFilesHelperTable.Bosses => "bosses.csv",
            CsvFilesHelperTable.Cards => "cards.csv",
            CsvFilesHelperTable.Animations => "animations.csv",
            CsvFilesHelperTable.Faces => "faces.csv",
            CsvFilesHelperTable.AllianceRoles => "alliance_roles.csv",
            CsvFilesHelperTable.AllianceBadges => "alliance_badges.csv",
            CsvFilesHelperTable.Tutorial => "tutorial.csv",
            CsvFilesHelperTable.Tiles => "tiles.csv",
            CsvFilesHelperTable.NameColors => "name_colors.csv",
            CsvFilesHelperTable.PlayerThumbnails => "player_thumbnails.csv",
            CsvFilesHelperTable.Skins => "skins.csv",
            CsvFilesHelperTable.Themes => "themes.csv",
            CsvFilesHelperTable.SkinConfs => "skin_confs.csv",
            CsvFilesHelperTable.Sprays => "sprays.csv",
            CsvFilesHelperTable.Hints => "hints.csv",
            CsvFilesHelperTable.Links => "links.csv",
            CsvFilesHelperTable.EmoteBundles => "emote_bundles.csv",
            CsvFilesHelperTable.PlayerMapEnvironments => "player_map_environments.csv",
            CsvFilesHelperTable.MapTemplates => "map_templates.csv",
            CsvFilesHelperTable.RankedLocations => "ranked_locations.csv",
            CsvFilesHelperTable.RankedRanks => "ranked_ranks.csv",
            CsvFilesHelperTable.Carryables => "carryables.csv",
            CsvFilesHelperTable.GearBoosts => "gear_boosts.csv",
            CsvFilesHelperTable.GearLevels => "gear_levels.csv",
            CsvFilesHelperTable.AllianceLeagueModes => "alliance_league_modes.csv",
            CsvFilesHelperTable.AllianceLeagueRanks => "alliance_league_ranks.csv",
            CsvFilesHelperTable.ShopPanelLayouts => "shop_panel_layouts.csv",
            CsvFilesHelperTable.ShopStyleSets => "shop_style_sets.csv",
            _ => throw new ArgumentOutOfRangeException(nameof(fileId), fileId, null)
        };
    }

    public static int GetId(this CsvFilesHelperTable fileId)
    {
        return fileId switch
        {
            CsvFilesHelperTable.TextsPatch => 0,
            CsvFilesHelperTable.Locales => 1,
            CsvFilesHelperTable.BillingPackages => 2,
            CsvFilesHelperTable.Globals => 3,
            CsvFilesHelperTable.Sounds => 4,
            CsvFilesHelperTable.Resources => 5,
            CsvFilesHelperTable.Projectiles => 6,
            CsvFilesHelperTable.Effects => 7,
            CsvFilesHelperTable.AllianceBadges => 8,
            CsvFilesHelperTable.ClientGlobals => 9,
            CsvFilesHelperTable.ParticleEmitters => 10,
            CsvFilesHelperTable.HealthBars => 11,
            CsvFilesHelperTable.Music => 12,
            CsvFilesHelperTable.Credits => 13,
            CsvFilesHelperTable.Regions => 14,
            CsvFilesHelperTable.Locations => 15,
            CsvFilesHelperTable.Characters => 16,
            CsvFilesHelperTable.AreaEffects => 17,
            CsvFilesHelperTable.Items => 18,
            CsvFilesHelperTable.Maps => 19,
            CsvFilesHelperTable.Skills => 20,
            CsvFilesHelperTable.Campaign => 21,
            CsvFilesHelperTable.Bosses => 22,
            CsvFilesHelperTable.Cards => 23,
            CsvFilesHelperTable.Animations => 24,
            CsvFilesHelperTable.AllianceRoles => 25,
            CsvFilesHelperTable.Tutorial => 26,
            CsvFilesHelperTable.Tiles => 27,
            CsvFilesHelperTable.PlayerThumbnails => 28,
            CsvFilesHelperTable.Skins => 29,
            CsvFilesHelperTable.Faces => 30,
            CsvFilesHelperTable.GameModeVariation => 33,
            CsvFilesHelperTable.Hints => 36,
            CsvFilesHelperTable.Milestones => 39,
            CsvFilesHelperTable.Messages => 40,
            CsvFilesHelperTable.Themes => 41,
            CsvFilesHelperTable.Links => 42,
            CsvFilesHelperTable.NameColors => 43,
            CsvFilesHelperTable.SkinConfs => 44,
            CsvFilesHelperTable.Accessories => 50,
            CsvFilesHelperTable.Emotes => 52,
            CsvFilesHelperTable.EmoteBundles => 53,
            CsvFilesHelperTable.PlayerMapEnvironments => 54,
            CsvFilesHelperTable.MapTemplates => 55,
            CsvFilesHelperTable.LocationThemes => 56,
            CsvFilesHelperTable.RankedRanks => 58,
            CsvFilesHelperTable.RankedLocations => 59,
            CsvFilesHelperTable.Carryables => 60,
            CsvFilesHelperTable.GearLevels => 61,
            CsvFilesHelperTable.GearBoosts => 62,
            CsvFilesHelperTable.AllianceLeagueModes => 63,
            CsvFilesHelperTable.AllianceLeagueRanks => 64,
            CsvFilesHelperTable.Sprays => 68,
            CsvFilesHelperTable.ShopPanelLayouts => 69,
            CsvFilesHelperTable.ShopStyleSets => 70,

            _ => throw new ArgumentOutOfRangeException(nameof(fileId), fileId, null)
        };
    }
}